
#Machine Energy Usage Config. This config is synced from server to client.
[usage]
	#Energy per operation tick (Joules).
	enrichmentChamber = "2147483647"
	#Energy per operation tick (Joules).
	osmiumCompressor = "2147483647"
	#Energy per operation tick (Joules).
	combiner = "2147483647"
	#Energy per operation tick (Joules).
	crusher = "2147483647"
	#Energy per operation tick (Joules).
	metallurgicInfuser = "2147483647"
	#Energy per operation tick (Joules).
	purificationChamber = "2147483647"
	#Energy per operation tick (Joules).
	energizedSmelter = "2147483647"
	#Energy per operation tick (Joules).
	digitalMiner = "2147483647"
	#Energy per operation tick (Joules).
	electricPump = "2147483647"
	#Energy that can be transferred at once per charge operation (Joules).
	chargePad = "1024000"
	#Energy per operation tick (Joules).
	rotaryCondensentrator = "2147483647"
	#Energy per operation tick (Joules).
	oxidationChamber = "2147483647"
	#Energy per operation tick (Joules).
	chemicalInfuser = "2147483647"
	#Energy per operation tick (Joules).
	chemicalInjectionChamber = "2147483647"
	#Energy per operation tick (Joules).
	precisionSawmill = "2147483647"
	#Energy per operation tick (Joules).
	chemicalDissolutionChamber = "2147483647"
	#Energy per operation tick (Joules).
	chemicalWasher = "2147483647"
	#Energy per operation tick (Joules).
	chemicalCrystallizer = "2147483647"
	#Energy per operation tick (Joules).
	seismicVibrator = "2147483647"
	#Energy per operation tick (Joules).
	pressurizedReactionBase = "2147483647"
	#Energy per operation tick (Joules).
	fluidicPlenisher = "100"
	#Energy per operation tick (Joules).
	laser = "10000"
	#Energy per operation tick (Joules).
	formulaicAssemblicator = "2147483647"
	#Energy per operation tick (Joules).
	modificationStation = "100"
	#Energy per operation tick (Joules).
	isotopicCentrifuge = "2147483647"
	#Energy per operation tick (Joules).
	nutritionalLiquifier = "2147483647"
	#Energy per operation tick (Joules).
	antiprotonicNucleosynthesizer = "2147483647"
	#Energy per operation tick (Joules).
	pigmentExtractor = "2147483647"
	#Energy per operation tick (Joules).
	pigmentMixer = "2147483647"
	#Energy per operation tick (Joules).
	paintingMachine = "2147483647"
	#Energy per chunk per tick (Joules).
	dimensionalStabilizer = "5000"

	#Teleporter
	[usage.teleporter]
		#Base Joules cost for a teleportation.
		teleporterBase = "1000"
		#Joules per unit of distance travelled during teleportation - sqrt(xDiff^2 + yDiff^2 + zDiff^2).
		teleporterDistance = "10"
		#Flat additional cost for interdimensional teleportation. Distance is still taken into account minimizing energy cost based on dimension scales.
		teleporterDimensionPenalty = "10000"

