Platform.mods.kubejs.name = "Crops 'N Cogs"
Platform.mods.mbd2.name = "Crops 'N Cogs"
Platform.mods.gtceu.name = "GTCEuM (NOT PERMANENT, WILL BE NUKED AT A LATER DATE)"
Platform.mods.mekanism.name = "Mekanism (NOT PERMANENT, WILL BE NUKED AT A LATER DATE)" 
Platform.mods.pneumaticcraft.name = "Pneumaticraft (NOT PERMANENT, WILL BE NUKED AT A LATER DATE)"